# #####################################################################
# Automatically generated by qmake (2.01a) Sa Mrz 28 23:14:48 2009
# #####################################################################
QT += network \
    webkit
TEMPLATE = app
TARGET = imgeval
DEPENDPATH += . \
    qtc-gdbmacros
RC_FILE = imgeval.rc
INCLUDEPATH += . \
    gui_graphs \
    ./includes

# Input
HEADERS += gui_graphs/atomimg.h \
    gui_graphs/datacurve.h \
    gui_graphs/graphaxis.h \
    gui_graphs/graphplotter.h \
    parambox.h \
    gui_graphs/imagemonitor.h \
    gui_graphs/scrollview.h \
    gui_graphs/regionofinterest.h \
    mainwindow.h \
    constants.h \
    savemode_gui/savemode.h \
    fits/fitstructs.h \
    fits/fitfunctions_gauss_bose.h \
    fits/fitfunctions_bimodal.h \
    fits/fitfunctions.h \
    fits/perform_fits.h \
    datastructure/imgdata.h \
    datastructure/dataset.h \
    savemode_gui/filesavebox.h \
    gui_settings/settingsquick.h \
    gui_settings/settingscontrol.h \
    input/inputlistthread.h \
    input/inputlist.h \
    datastructure/numeric_templates.h \
    gui_settings/setting_vector_edit.h \
    image_calc/fftwfilter.h \
    gui_graphs/imagemarker.h \
    fits/fitfunctions2d.h \
    gui_settings/interpreter_gui.h \
    input/loadtostack.h \
    fits/errpattern.h \
    input/errorpatterngui.h
SOURCES += gui_graphs/atomimg.cpp \
    gui_graphs/datacurve.cpp \
    gui_graphs/graphaxis.cpp \
    gui_graphs/graphplotter.cpp \
    parambox.cpp \
    gui_graphs/imagemonitor.cpp \
    gui_graphs/scrollview.cpp \
    gui_graphs/regionofinterest.cpp \
    main.cpp \
    mainwindow.cpp \
    savemode_gui/savemode.cpp \
    fits/perform_fits.cpp \
    fits/fitfunctions_gauss_bose.cpp \
    fits/fitfunctions_bimodal.cpp \
    fits/fitfunctions.cpp \
    datastructure/imgdata.cpp \
    datastructure/dataset.cpp \
    savemode_gui/filesavebox.cpp \
    gui_settings/settingsquick.cpp \
    gui_settings/settingscontrol.cpp \
    input/inputlistthread.cpp \
    input/inputlist.cpp \
    gui_settings/setting_vector_edit.cpp \
    image_calc/fftwfilter.cpp \
    gui_graphs/imagemarker.cpp \
    fits/fitfunctions2d.cpp \
    gui_settings/interpreter_gui.cpp \
    input/loadtostack.cpp \
    fits/errpattern.cpp \
    input/errorpatterngui.cpp
LIBS += -lgsl \
    -L \
    . \
    -L \
    ./release \
    -lgslcblas \
    -lm \
    -lmat \
    -lmx
win32:LIBS += -lfftw3-3
!win32:LIBS += -lfftw3
DEFINES += HAVE_INLINE
INCLUDES += /usr/include
win32 { 
    INCLUDEPATH += D:/Programs/GnuWin32/include
    CONFIG += -static-libgcc
    CONFIG += CONSOLE
}
OTHER_FILES += imgeval.ico \
    imgeval.rc \
    doc/TIFF6.pdf
